# Copyright 2022 Octopus Network
# SPDX-License-Identifier: LGPL-3.0-only

site_name: ChainBridge Docs
site_description: Modular Multi-Directional Blockchain Bridge to interact with Multiple Networks; Ethereum, Ethereum Classic, Substrate, Cosmos-SDK based chains.

repo_name: octopus/chainbridge
repo_url: https://github.com/octopus-network/ChainBridge

# Configuration
markdown_extensions:
  - meta
  - admonition
  - codehilite
  - toc:
      permalink: true

theme:
  name: material
  palette:
    primary: black
  favicon: img/favicon.ico
nav:
  - Overview: index.md
  - Specification:
      - ChainBridge: spec.md
      - Ethereum:
          - Bridge Setup: chains/ethereum.md
          - Contracts: chains/eth-contracts.md
      - Substrate: chains/substrate.md
  - Deploy & Test Guides:
      - Install & config Relayer:
          - Installation: installation.md
          - Configuration:
              - Overview: configuration.md
              - CLI Options: cli-options.md
      - Running Locally (EVM <-> Sub):
          - EVM <-> Sub1: local1.md
          - EVM <-> Sub2: local2.md
      - Deploying Live (EVM <-> EVM): live-evm-bridge.md
  - FAQ: faq.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/octopus-network/ChainBridge
